"""fixed user table cascade spelling and kwargs and relationship

Revision ID: 7dd03435cb07
Revises: f4bed434b134
Create Date: 2026-07-01 20:12:26.660009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd03435cb07'
down_revision: Union[str, Sequence[str], None] = 'f4bed434b134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
