"""added slug field in category table

Revision ID: c3fe4c092bf0
Revises: 328390f7c9b6
Create Date: 2026-09-12 04:32:44.614436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3fe4c092bf0'
down_revision: Union[str, Sequence[str], None] = '328390f7c9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.alter_column('shipping_status', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_status', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
